language: python
python:
  - "2.7"
  - "3.5"
env:
  matrix:
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"

# command to install dependencies
install:
  - pip install -I -q Django$DJANGO_VERSION
  - python setup.py install
# command to run tests
script:
  - DJANGO_SETTINGS_MODULE=inmemorystorage.test_settings python setup.py test
